const tournamentTeam = [
    "Pakistan",
    "India",
    "Australia",
    "New Zealand",
    "England",
    "Afghanistan",
    "Namibia",
    "Scotland",
    "Sri Lanka",
    "South Africa",
    "Netherlands",
  ];
  const arrayOfTeam = {
    Pakistan: [
      "Babar Azam",
      "Mohammad Rizwan",
      "Fakhar Zaman",
      "Mohammad Hafeez",
      "Shoaib Malik",
      "Shadab Khan",
      "Imad Wasim",
      "Asif Ali",
      "Haris Rauf",
      "Hasan Ali",
      "Shaheen Shah Afridi",
    ],
    India: [
      "Virat Kohli",
      "Rohit Sharma",
      "KL Rahul",
      "Rishabh Pant",
      "Ishan Kishan",
      "Suryakumar Yadav",
      "Hardik Pandya",
      "Ravindra Jadeja",
      "Rahul Chahar",
      "Ravichandran Ashwin",
      "Mohammed Shami",
    ],
    Australia: [
      "Aaron Finch",
      "Pat Cummins",
      "Josh Hazlewood",
      "Josh Inglis",
      "Glenn Maxwell",
      "Kane Richardson",
      "Mitchell Marsh",
      "Steve Smith",
      "David Warner",
      "Adam Zampa",
      "Ashton Agar",
    ],
    "New Zealand": [
      "Kane Williamson",
      "Tim Seifert",
      "Martin Guptill",
      "Todd Astle",
      "Trent Boult",
      "Mark Chapman",
      "Devon Conway",
      "Adam Milne",
      "Kyle Jamieson",
      "Daryl Mitchell",
      "Tim Southee",
    ],
    England: [
      "Eoin Morgan",
      "Jos Buttler",
      "Moeen Ali",
      "Jonny Bairstow",
      "Sam Billings",
      "Tom Curran",
      "Chris Jordan",
      "Dawid Malan",
      "Tymal Mills",
      "David Willey",
      "Mark Wood",
    ],
    Afghanistan: [
      "Mohammad Nabi",
      "Rashid Khan",
      "Mujeeb Ur Rahman",
      "Usman Ghani",
      "Mohammad Shahzad",
      "Rahmanullah Gurbaz",
      "Hashmatullah Shahidi",
      "Asghar Afghan",
      "Najibullah Zadran",
      "Hazratullah Zazai",
      "Naveen ul Haq",
    ],
    Namibia: [
      "Gerhard Erasmus",
      "Stephen Baard",
      "Karl Birkenstock",
      "Michau du Preez",
      "Jan Frylinck",
      "Zane Green",
      "Nicol Lofie-Eaton",
      "Ben Shikongo",
      "Michael van Lingen",
      "Craig Williams",
      "Pikky Ya France",
    ],
    Scotland: [
      "Kyle Coetzer",
      "Richard Berrington",
      "Dylan Budge",
      "Mark Watt",
      "Matthew Cross",
      "Josh Davey",
      "Michael Leask",
      "Calum Macleod",
      "George Munsey",
      "Hamza Tahir",
      "Brad Wheal",
    ],
    "Sri Lanka": [
      "Dasun Shanaka",
      "Kusal Perera",
      "Dinesh Chandimal",
      "Dhananjaya de Silva",
      "Charith Asalanka",
      "Avishka Fernando",
      "Chamika Karunaratne",
      "Wanindu Hasaranga",
      "Akila Dananjaya",
      "Pathum Nissanka",
      "Bhanuka Rajapaksa",
    ],
    "South Africa": [
      "Temba Bavuma",
      "Quinton de Kock",
      "Aiden Markram",
      "David Miller",
      "Keshav Maharaj",
      "Bjorn Fortuin",
      "Reeza Hendricks",
      "Heinrich Klaasen",
      "Wiaan Mulder",
      "Lungi Ngidi",
      "Rassie van der Dussen",
    ],
    Netherlands: [
      "Pieter Seelaar",
      "Colin Ackermann",
      "Ben Cooper",
      "Philippe Boissevain",
      "Bas de Leede",
      "Scott Edwards",
      "Brandon Glover",
      "Fred Klaassen",
      "Stephan Myburgh",
      "Ryan ten Doeschate",
      "Paul van Meekeren",
    ],
  };
  
  export { tournamentTeam, arrayOfTeam };
  